version: "3.9"
services:
  back:
    build:
      context: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '3000:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  front:
    build:
      context: ./frontend
    restart: always
    environment:
      VUE_APP_BASE_URL: http://localhost:3000/api
    ports:
      - '8080:8080'
